### ISSUE TITLE
[Enhancement] Integration of Firebase Cloud Messaging API

### ISSUE THREAD

**Issue by AndreasReitberger** [DanJunior78/Repetier-Server-Telegram-Bot#12]
Hi @DanJunior78 

I'm making an iOS and Android app for the Repetier Server. For this, I want to enable push notifications. However, Repetier Server has no integration for this and the channel for the official "Informer" App is not public.
Your plugin does already a good job, so I wanted to ask if you can create another one using the Firebase Cloud Messaging API instead of the Telegram API?
https://medium.com/devmins/firebase-cloud-messaging-api-with-python-6c0755e41eb5

Thanks,
Andreas

**Comment by DanJunior78** [comment]
Hello Andreas,

I had a look on it. Everything is possible. I'll have a look and check, if I find some time to get into it. 
Regards Daniel
