### ISSUE TITLE
Bilder / Videos senden / send pictures /vids 

### ISSUE THREAD

**Issue by Excellsior1985** [DanJunior78/Repetier-Server-Telegram-Bot#4]
DEU:

Hallo ich habe den Bot samt Repetier auf einem Windows Server laufen.

Die Kommunikation etc funktioniert.
Mein Problem ist das keine Bilder, Gifs oder Videos versendet werden können.

Die ausgabe in der CMD sagt:

> **OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-95hbg2jt\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): F:\Repetier-Server-Telegram-Bot\vid\Sidewinder\Sidewinder.avi in function 'cv::icvExtractPattern'**

Im Botlog findet sich:

> `(Bot:1381193963:dispatcher) - 2020-11-24 12:29:16,432 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(55        ) - 2020-11-24 12:29:17,014 - Main Thread - INFO - MessageID 55 von der chatID  wurde gelöscht 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:17,199 - Main Thread - INFO - checkMsgID: Drucker Sidewinder fordert neue MessageID für MessageID an: 53 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:17,329 - WS Thread - INFO - keepBasicPrinterInfo: Drucker Sidewinder erzeugt neue MessageID: 56 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:18,612 - apscheduler.scheduler - INFO - Removed job 83bd23186dc64590aba0de3b2327a638 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:18,801 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:20,930 - apscheduler.scheduler - INFO - Removed job 66f3056e3ff24028b0102002c02c7928 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:20,931 - WS Thread - INFO - Thread initialisiert: Sende Gif 1 
(Sende Gif 1) - 2020-11-24 12:29:21,144 - WS Thread - INFO - Gif Erstellung startet für Sidewinder
 
(Sende Gif 1) - 2020-11-24 12:29:21,145 - WS Thread - CRITICAL - Lösche F:\Repetier-Server-Telegram-Bot\pic\gif\Sidewinder\Sidewinder.gif 
(54        ) - 2020-11-24 12:29:25,151 - Main Thread - INFO - MessageID 54 von der chatID 64063243 wurde gelöscht 
(Sende Gif 1) - 2020-11-24 12:29:26,573 - WS Thread - INFO - png Erstellung beendet für Sidewinder 
(Sende Gif 1) - 2020-11-24 12:29:26,754 - WS Thread - ERROR - Erstellungsfehler imageio.mimsave in buildGif für Drucker: Sidewinder 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:31,197 - Main Thread - INFO - Thread initialisiert für Drucker: Communication Message und MessageID: 57 mit er Laufzeit: 0:00:01s 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:31,519 - Main Thread - INFO - updatePrinterMsgReplayMarkup: Drucker Sidewinder löscht MessageID: 56 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:31,624 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:32,176 - apscheduler.scheduler - INFO - Removed job 0ab907753ff04a818070b02371285d34 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:32,176 - Main Thread - INFO - Thread initialisiert für Drucker: Communication Message und MessageID: 58 mit er Laufzeit: 0:00:01s 
(57        ) - 2020-11-24 12:29:32,293 - Main Thread - INFO - MessageID 57 von der chatID  wurde gelöscht 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:32,525 - Main Thread - ERROR - Bot Bad Request "Message to edit not found" 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:33,098 - Main Thread - INFO - checkMsgID: Drucker Sidewinder fordert neue MessageID für MessageID an: 56 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:33,214 - WS Thread - INFO - keepBasicPrinterInfo: Drucker Sidewinder erzeugt neue MessageID: 60 
(58        ) - 2020-11-24 12:29:33,306 - Main Thread - INFO - MessageID 58 von der chatID  wurde gelöscht 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:34,439 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:35,637 - apscheduler.scheduler - INFO - Removed job 8e4462498054492c8b5a19b1792d321c 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:35,638 - WS Thread - INFO - Thread initialisiert: Sende Video 1 
(Sende Video 1) - 2020-11-24 12:29:35,852 - WS Thread - INFO - Vid Erstellung startet für Sidewinder
 
(Sende Video 1) - 2020-11-24 12:29:36,215 - WS Thread - INFO - Vid Erstellung beendet für Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,338 - WS Thread - INFO - Vid Caption Erstellung beendet für Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,744 - WS Thread - ERROR - Sendefehler telegramSendPic in buildGif für Drucker: Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,745 - WS Thread - INFO - Vid versendet für Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,746 - Main Thread - INFO - Thread initialisiert für Drucker: Sidewinder und MessageID: 60 mit er Laufzeit: 0:00:01s 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:37,597 - Main Thread - INFO - checkMsgID: Drucker Sidewinder fordert neue MessageID für MessageID an: 60 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:37,723 - WS Thread - INFO - keepBasicPrinterInfo: Drucker Sidewinder erzeugt neue MessageID: 61 
(60        ) - 2020-11-24 12:29:37,853 - Main Thread - INFO - MessageID 60 von der chatID  wurde gelöscht `

________________________________________________

Eine suche im Netz führte mich hier hin:

https://answers.opencv.org/question/220468/video-from-ip-camera-cant-find-starting-number-cvicvextractpattern/

![image](https://user-images.githubusercontent.com/74668515/100089402-e8ece500-2e51-11eb-8e35-ddd82f9ff844.png)

Auf einem Windows Server wird es aber schwer einen IP Stream ohne Port zu realisieren.

Auf der Repetier Seite selbst wird ebenfalls nur die Lösung inkl. Port angeboten.

Hast du da eine Lösung?

ENG:

Hello I have the bot and repetier running on a Windows server.

The communication etc. works.
My problem is that no pictures, gifs or videos can be sent.

The output in the CMD says:

> **OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-95hbg2jt\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): F:\Repetier-Server-Telegram-Bot\vid\Sidewinder\Sidewinder.avi in function 'cv::icvExtractPattern'**

Im Botlog findet sich:

> `(Bot:1381193963:dispatcher) - 2020-11-24 12:29:16,432 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(55        ) - 2020-11-24 12:29:17,014 - Main Thread - INFO - MessageID 55 von der chatID  wurde gelöscht 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:17,199 - Main Thread - INFO - checkMsgID: Drucker Sidewinder fordert neue MessageID für MessageID an: 53 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:17,329 - WS Thread - INFO - keepBasicPrinterInfo: Drucker Sidewinder erzeugt neue MessageID: 56 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:18,612 - apscheduler.scheduler - INFO - Removed job 83bd23186dc64590aba0de3b2327a638 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:18,801 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:20,930 - apscheduler.scheduler - INFO - Removed job 66f3056e3ff24028b0102002c02c7928 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:20,931 - WS Thread - INFO - Thread initialisiert: Sende Gif 1 
(Sende Gif 1) - 2020-11-24 12:29:21,144 - WS Thread - INFO - Gif Erstellung startet für Sidewinder
 
(Sende Gif 1) - 2020-11-24 12:29:21,145 - WS Thread - CRITICAL - Lösche F:\Repetier-Server-Telegram-Bot\pic\gif\Sidewinder\Sidewinder.gif 
(54        ) - 2020-11-24 12:29:25,151 - Main Thread - INFO - MessageID 54 von der chatID 64063243 wurde gelöscht 
(Sende Gif 1) - 2020-11-24 12:29:26,573 - WS Thread - INFO - png Erstellung beendet für Sidewinder 
(Sende Gif 1) - 2020-11-24 12:29:26,754 - WS Thread - ERROR - Erstellungsfehler imageio.mimsave in buildGif für Drucker: Sidewinder 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:31,197 - Main Thread - INFO - Thread initialisiert für Drucker: Communication Message und MessageID: 57 mit er Laufzeit: 0:00:01s 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:31,519 - Main Thread - INFO - updatePrinterMsgReplayMarkup: Drucker Sidewinder löscht MessageID: 56 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:31,624 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:32,176 - apscheduler.scheduler - INFO - Removed job 0ab907753ff04a818070b02371285d34 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:32,176 - Main Thread - INFO - Thread initialisiert für Drucker: Communication Message und MessageID: 58 mit er Laufzeit: 0:00:01s 
(57        ) - 2020-11-24 12:29:32,293 - Main Thread - INFO - MessageID 57 von der chatID  wurde gelöscht 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:32,525 - Main Thread - ERROR - Bot Bad Request "Message to edit not found" 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:33,098 - Main Thread - INFO - checkMsgID: Drucker Sidewinder fordert neue MessageID für MessageID an: 56 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:33,214 - WS Thread - INFO - keepBasicPrinterInfo: Drucker Sidewinder erzeugt neue MessageID: 60 
(58        ) - 2020-11-24 12:29:33,306 - Main Thread - INFO - MessageID 58 von der chatID  wurde gelöscht 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:34,439 - apscheduler.scheduler - INFO - Added job "_trigger_timeout" to job store "default" 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:35,637 - apscheduler.scheduler - INFO - Removed job 8e4462498054492c8b5a19b1792d321c 
(Bot:1381193963:dispatcher) - 2020-11-24 12:29:35,638 - WS Thread - INFO - Thread initialisiert: Sende Video 1 
(Sende Video 1) - 2020-11-24 12:29:35,852 - WS Thread - INFO - Vid Erstellung startet für Sidewinder
 
(Sende Video 1) - 2020-11-24 12:29:36,215 - WS Thread - INFO - Vid Erstellung beendet für Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,338 - WS Thread - INFO - Vid Caption Erstellung beendet für Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,744 - WS Thread - ERROR - Sendefehler telegramSendPic in buildGif für Drucker: Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,745 - WS Thread - INFO - Vid versendet für Sidewinder 
(Sende Video 1) - 2020-11-24 12:29:36,746 - Main Thread - INFO - Thread initialisiert für Drucker: Sidewinder und MessageID: 60 mit er Laufzeit: 0:00:01s 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:37,597 - Main Thread - INFO - checkMsgID: Drucker Sidewinder fordert neue MessageID für MessageID an: 60 
(Repetier-Server-Order-Data) - 2020-11-24 12:29:37,723 - WS Thread - INFO - keepBasicPrinterInfo: Drucker Sidewinder erzeugt neue MessageID: 61 
(60        ) - 2020-11-24 12:29:37,853 - Main Thread - INFO - MessageID 60 von der chatID  wurde gelöscht `

A search on the net led me here:

https://answers.opencv.org/question/220468/video-from-ip-camera-cant-find-starting-number-cvicvextractpattern/

![image](https://user-images.githubusercontent.com/74668515/100089402-e8ece500-2e51-11eb-8e35-ddd82f9ff844.png)

But on a Windows server it will be difficult to realize an IP stream without a port.

On the repetier side itself, only the solution including port is offered.

Do you have a solution?

**Comment by DanJunior78** [comment]
Ok, besser in englisch.
I am using a RPi as server. I am using the stream and snapshot like following:
http://127.0.0.1:8081/?action=stream
http://127.0.0.1:8081/?action=snapshot
in my program i am exchanging the local IP to the access IP (e.g. 127.0.01 -> 192.168.90.30) 
All is based on the Repetier solution. I´ve privately my home automation with security cameras programmed. There i´ve used on a security camera an Apache server to download videos and pictures.
Did you try to change your links to something similar, as i mentioned above? 
On my Win10 PC it is working...but i´ve the repetier server on my RPi...  
But it should work with this parameters, which I mentioned.

**Comment by Excellsior1985** [comment]
DEU:

Das ist bei mir ebenso der Fall.
Ich habe einen Blueiris Server für die Kameras laufen.
Dieser und auch alle anderen mir bekannten Windows webstream Server müssen zwangsläufig einen Port bei der Kamera mit angeben.

Ich versuche es dann mal weiter.
Danke auf jeden Fall für die Rückmeldung

ENG:

This is also the case with me.
I have a Blueiris server running for the cameras.
This server and all other Windows webstream servers I know of have to specify a port for the camera.

I will try it further.
Thanks in any case for the feedback

**Comment by DanJunior78** [comment]
Ahhh, also, ich habe die Anfrage strikt an die  Repetier Server Anbindung programmiert.
Diese kannst Du im Code relativ leicht nachvollziehen. 
Die PNGs und GIFs werden aus statischen Bildern generiert. 
Das Video aus einem Stream. 
Vielleicht kannst Du mir ja, falls Du über den Browser, Bilder und Videos direkt streamen kannst, die Adressierungsart zukommen lassen. Dann fällt mir evtl. auch etwas dazu ein. Ich könnte es ja,falls es nicht zu kompliziert ist, parametrierbar machen.

**Comment by DanJunior78** [comment]
Bist Du weiter gekommen?

**Comment by DanJunior78** [comment]
Sollte erledigt sein...
