### ISSUE TITLE
Bug in V041

### ISSUE THREAD

**Issue by DanJunior78** [DanJunior78/Repetier-Server-Telegram-Bot#6]
Please be aware there is still a bug in this version which makes still some trouble. Please be aware about it. I´ll push the next update after certain tests to be sure that it is all in safe state.

**Comment by SebiWolze** [comment]
Any news?
Thanks.

**Comment by DanJunior78** [comment]
Yes, I did find the bug...latest tomorrow I'll upload an update.

**Comment by DanJunior78** [comment]
I am working on the version 1.0 ... the latest version 0.5 runs smooth on my system and reliable. Please be aware i´ve removed the message notification due to exceeding the telegram limits. There might be some problems running more then 3 printers on one server.
This will be solved with the version 1.0 and for the future. Please be patient because i am rewriting the core for the program and i´ll test it a certain time.

**Comment by SebiWolze** [comment]
If you need/want somebody to test - feel free to ask me or contact me via Telegram @Sebi91
